name: Node.js Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        package: [packages/logger packages/oauth packages/rtm-api packages/socket-mode packages/types packages/web-api packages/webhook]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Get Development Dependencies
      run: npm i
    - name: Build and Run Tests in Each Package
      working-directory: ${{ matrix.package }}
      run: |
        npm install || npm list
        npm test
